### ISSUE TITLE
OnAchievement is very spammy

### ISSUE THREAD

**Issue by GlorifiedPig** [Jaskowicz1/Minecraft-Discord-Relay#3]
OnAchievement is very spammy: https://github.com/Jaskowicz1/Minecraft-Discord-Relay/blob/master/src/main/java/me/jaskowicz/minecraftdiscordrelay/Listeners/OnAchievement.java

It prints out whenever someone even gets a recipe, so simply just playing on the server spams the chat with "x completed recipe_x"

**Comment by Jaskowicz1** [comment]
Noticed that myself recently, have thought about removing it and was awaiting thoughts from others. I'll push an update out in a few minutes and remove the achievement announcement.

**Comment by GlorifiedPig** [comment]
Example: https://i.imgur.com/nJ5E7kf.png

**Comment by GlorifiedPig** [comment]
> 
> 
> Noticed that myself recently, have thought about removing it and was awaiting thoughts from others. I'll push an update out in a few minutes and remove the achievement announcement.

Thanks, very much appreciated :)

**Comment by Jaskowicz1** [comment]
> Example: https://i.imgur.com/nJ5E7kf.png

Oh wow that is rather spammy haha, yeah I'll put the release out when I've finished my lunch 😀

**Comment by GlorifiedPig** [comment]
Maybe you could make it so that it only sends it for the actual achievements from the advancements tree gets sent? And send the description instead of the "husbandry/root" style name, like it does it in the chat sort of

**Comment by Jaskowicz1** [comment]
> Maybe you could make it so that it only sends it for the actual achievements from the advancements tree gets sent? And send the description instead of the "husbandry/root" style name, like it does it in the chat sort of

I can, however, it'll take some time. The reason it says `husbandry/root` is because that's the localised format for clients to translate. I'll continue to work on it but I can't say it'll be done very soon.

**Comment by Jaskowicz1** [comment]
Just want to mention, it's been fixed in the recent release https://github.com/Jaskowicz1/Minecraft-Discord-Relay/releases/tag/v1.1.6

**Comment by GlorifiedPig** [comment]
Thanks, I have added the latest version to my server 😃
