### ISSUE TITLE
guildID - What is this?

### ISSUE THREAD

**Issue by GamingXboxSanok** [Jaskowicz1/Minecraft-Discord-Relay#6]
guildID - What is this?
I don't know, and plugin on my server don't working.

**Comment by Jaskowicz1** [comment]
The guild ID is the ID of your server, right click your server icon at the left of discord and copy the ID

**Comment by GamingXboxSanok** [comment]
Hmm, interesting. On my Discord, my bot shows that there is 1 player on the server (this is currently true), but if I write something in the chat, it does not show on the channel: /
