### ISSUE TITLE
Minecraft Chat on Discord isn't working

### ISSUE THREAD

**Issue by GamingXboxSanok** [Jaskowicz1/Minecraft-Discord-Relay#7]
On my Discord, my bot shows that there is 1 player on the server (this is currently true), but if I write something in the chat, it does not show on the channel :/

On server console, I got messages like this:
[INFO] [MinecraftDiscordRelay(MCDR)] Enabling MinecraftDiscordRelay v1.1.6
[INFO] [MinecraftDiscordRelay(MCDR)] Loading config...
[INFO] [MinecraftDiscordRelay(MCDR)] Config loaded successfully!
[INFO] [MinecraftDiscordRelay(MCDR)] Config checks finished!
[INFO] [MinecraftDiscordRelay(MCDR)] Loading bot...
[INFO] [MinecraftDiscordRelay(MCDR)] Bot loaded successfully!
[INFO] [MinecraftDiscordRelay(MCDR)] Starting logger listener...
[INFO] [MinecraftDiscordRelay(MCDR)] Loaded console logger!
[INFO] [MinecraftDiscordRelay(MCDR)] Registering Listeners...
[INFO] [MinecraftDiscordRelay(MCDR)] Registered Listeners!
[INFO] [MinecraftDiscordRelay(MCDR)] Finished loading Minecraft Discord Relay (MCDR)!

It looks like it's supposed to work!

**Comment by Jaskowicz1** [comment]
It looks like you're using the outdated version, the old versions use an old version of the Discord API and no longer work so you'll need to update to 1.2!

**Comment by Jaskowicz1** [comment]
Ahh I see why you have the outdated, I forgot to update the spigot site :P
